// <auto-generated />
using System;
using ClientService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClientService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ClientDbContext))]
    partial class ClientDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClientService.Domain.Entities.Authentification", b =>
            {
                b.Property<Guid>("AuthentificationId").HasColumnType("uuid");
                b.Property<Guid>("ClientId").HasColumnType("uuid");
                b.Property<string>("Login").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<bool>("MfaActive").HasColumnType("boolean");
                b.Property<string>("MotDePasse").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
                b.HasKey("AuthentificationId");
                b.HasIndex("ClientId").IsUnique();
                b.ToTable("Authentifications");
            });

            modelBuilder.Entity("ClientService.Domain.Entities.Client", b =>
            {
                b.Property<Guid>("ClientId").HasColumnType("uuid");
                b.Property<string>("Adresse").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
                b.Property<string>("NasSimule").IsRequired().HasMaxLength(11).HasColumnType("character varying(11)");
                b.Property<string>("Nom").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("Statut").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                b.HasKey("ClientId");
                b.ToTable("Clients");
            });

            modelBuilder.Entity("ClientService.Domain.Entities.Session", b =>
            {
                b.Property<Guid>("SessionId").HasColumnType("uuid");
                b.Property<Guid>("ClientId").HasColumnType("uuid");
                b.Property<DateTime>("DateCreation").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("DateExpiration").HasColumnType("timestamp with time zone");
                b.HasKey("SessionId");
                b.HasIndex("ClientId");
                b.ToTable("Sessions");
            });

            modelBuilder.Entity("ClientService.Domain.Entities.VerificationKYC", b =>
            {
                b.Property<Guid>("VerificationKYCId").HasColumnType("uuid");
                b.Property<Guid>("ClientId").HasColumnType("uuid");
                b.Property<DateTime>("DateVerification").HasColumnType("timestamp with time zone");
                b.Property<bool>("Resultat").HasColumnType("boolean");
                b.HasKey("VerificationKYCId");
                b.HasIndex("ClientId").IsUnique();
                b.ToTable("VerificationKYCs");
            });

            modelBuilder.Entity("ClientService.Domain.Entities.Authentification", b =>
            {
                b.HasOne("ClientService.Domain.Entities.Client", "Client")
                    .WithOne("Authentification")
                    .HasForeignKey("ClientService.Domain.Entities.Authentification", "ClientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Client");
            });

            modelBuilder.Entity("ClientService.Domain.Entities.Session", b =>
            {
                b.HasOne("ClientService.Domain.Entities.Client", "Client")
                    .WithMany("Sessions")
                    .HasForeignKey("ClientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Client");
            });

            modelBuilder.Entity("ClientService.Domain.Entities.VerificationKYC", b =>
            {
                b.HasOne("ClientService.Domain.Entities.Client", "Client")
                    .WithOne("VerificationKYC")
                    .HasForeignKey("ClientService.Domain.Entities.VerificationKYC", "ClientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Client");
            });

            modelBuilder.Entity("ClientService.Domain.Entities.Client", b =>
            {
                b.Navigation("Authentification");
                b.Navigation("Sessions");
                b.Navigation("VerificationKYC");
            });
#pragma warning restore 612, 618
        }
    }
}
