{
 "title": "BankSimple — 4 Golden Signals",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Trafic",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total[1m]))",
     "legendFormat": "RPS total"
    }
   ]
  },
  {
   "title": "Erreurs",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code=~\"4..\"}[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(http_requests_received_total{code=~\"5..\"}[1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Latence",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "dotnet_total_memory_bytes", "legendFormat": "RAM {{job}}" }
   ]
  },
  {
   "title": "Saturation",
   "type": "stat",
   "gridPos": { "x": 0, "y": 16, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(http_requests_in_progress)", "legendFormat": "Requêtes en cours" }
   ]
  },
  {
   "title": "Saturation",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 16, "w": 18, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "CPU {{job}}"
    }
   ]
  }
 ]
}