// <auto-generated />
using System;
using PaymentService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace PaymentService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    partial class PaymentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PaymentService.Domain.Entities.Virement", b =>
            {
                b.Property<Guid>("VirementId").HasColumnType("uuid");
                b.Property<Guid>("CompteDestinataireId").HasColumnType("uuid");
                b.Property<Guid>("CompteSourceId").HasColumnType("uuid");
                b.Property<DateTime>("DateVirement").IsRequired().HasColumnType("timestamp with time zone");
                b.Property<decimal>("Montant").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                b.Property<string>("Statut").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                b.HasKey("VirementId");
                b.HasIndex("CompteSourceId");
                b.HasIndex("CompteDestinataireId");
                b.ToTable("Virements");
            });
#pragma warning restore 612, 618
        }
    }
}
