# Upstream avec least_conn pour distribuer la charge entre les replicas
upstream client_service {
    least_conn;
    server client-service:8080;
}

upstream account_service {
    least_conn;
    server account-service:8080;
}

upstream payment_service {
    least_conn;
    server payment-service:8080;
}

server {
    listen 80;

    location /api/v1/virements {
        proxy_pass http://payment_service;
    }

    location ~ ^/api/v1/clients/[^/]+/comptes {
        proxy_pass http://account_service;
    }

    location /api/v1 {
        proxy_pass http://client_service;
    }
}
