upstream client_backend {
    least_conn;
    server client-service:8080;
}

upstream account_backend {
    least_conn;
    server account-service:8080;
}

upstream payment_backend {
    least_conn;
    server payment-service:8080;
}

server {
    listen 80;

    location /api/v1/virements {proxy_pass http://payment_backend;}

    location ~ ^/api/v1/clients/[^/]+/comptes {proxy_pass http://account_backend;}

    location /api/v1 {proxy_pass http://client_backend;}
}
