server {
    listen 80;

    resolver 127.0.0.11 valid=10s ipv6=off;

    location /api/v1/virements {
        # variable DNS pour resoudre a chaque requete de payment service
        set $upstream_payment http://payment-service:8080;
        proxy_pass $upstream_payment;
    }

    location ~ ^/api/v1/clients/[^/]+/comptes {
        # variable DNS pour resoudre a chaque requete de account service
        set $upstream_account http://account-service:8080;
        proxy_pass $upstream_account;
    }

    location /api/v1 {
        # variable DNS pour resoudre a chaque requete de client service
        set $upstream_client http://client-service:8080;
        proxy_pass $upstream_client;
    }
}
