// <auto-generated />
using System;
using AccountService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccountService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AccountDbContext))]
    partial class AccountDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccountService.Domain.Entities.Compte", b =>
            {
                b.Property<Guid>("CompteId").HasColumnType("uuid");
                b.Property<Guid>("ClientId").HasColumnType("uuid");
                b.Property<DateTime>("DateOuverture").IsRequired().HasColumnType("timestamp with time zone");
                b.Property<decimal>("Solde").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                b.Property<string>("Statut").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                b.Property<string>("Type").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                b.HasKey("CompteId");
                b.HasIndex("ClientId");
                b.ToTable("Comptes");
            });
#pragma warning restore 612, 618
        }
    }
}
