@startuml composant
title BankSimple - Diagramme de Composants (UC-01 à UC-05)

left to right direction
skinparam linetype ortho

package "Api" <<Presentation>> {
    [ClientController]
    [AuthController]
    [AccountController]
    [PaymentController]
}

package "Application" <<Use Cases>> {
    package "Commands" {
        [WriteClient]
        [WriteAuthentification]
        [WriteAccount]
        [WriteVirement]
    }
    package "Queries" {
        [ReadClient]
        [ReadAccountBalance]
        [ReadTransactions]
    }
}

package "Domain" <<Core>> {
    [Client]
    [CompteBancaire]
    [Virement]
    [Transaction]
}

package "Infrastructure" <<Persistence>> {
    [ClientRepository]
    [AuthRepository]
    [AccountRepository]
    [TransactionRepository]
    database [DbContext]
}

' UC-01/02 — Auth
[AuthController] --> [WriteAuthentification]
[WriteAuthentification] --> [Client]
[WriteAuthentification] --> [AuthRepository]

' UC-01 — Inscription
[ClientController] --> [WriteClient]
[WriteClient] --> [Client]
[WriteClient] --> [ClientRepository]
[ClientController] --> [ReadClient]
[ReadClient] --> [ClientRepository]

' UC-03 — Ouverture de compte
[AccountController] --> [WriteAccount]
[WriteAccount] --> [CompteBancaire]
[WriteAccount] --> [AccountRepository]

' UC-04 — Consultation
[AccountController] --> [ReadAccountBalance]
[ReadAccountBalance] --> [AccountRepository]
[AccountController] --> [ReadTransactions]
[ReadTransactions] --> [TransactionRepository]

' UC-05 — Virement
[PaymentController] --> [WriteVirement]
[WriteVirement] --> [Virement]
[WriteVirement] --> [Transaction]
[WriteVirement] --> [TransactionRepository]

' Infrastructure
[ClientRepository] --> [DbContext]
[AuthRepository] --> [DbContext]
[AccountRepository] --> [DbContext]
[TransactionRepository] --> [DbContext]

@enduml
