name: CI

on:
  push:
    branches: [ main, master, upgrade-to-NET8 ]
  pull_request:

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: |
          dotnet restore src/services/ClientService/ClientService.Api/ClientService.Api.csproj
          dotnet restore src/services/AccountService/AccountService.Api/AccountService.Api.csproj
          dotnet restore src/services/PaymentService/PaymentService.Api/PaymentService.Api.csproj

      - name: Build ClientService
        run: dotnet build src/services/ClientService/ClientService.Api/ClientService.Api.csproj -c Release --no-restore

      - name: Build AccountService
        run: dotnet build src/services/AccountService/AccountService.Api/AccountService.Api.csproj -c Release --no-restore

      - name: Build PaymentService
        run: dotnet build src/services/PaymentService/PaymentService.Api/PaymentService.Api.csproj -c Release --no-restore

      - name: Run tests
        env:
          Jwt__Secret: ${{ secrets.JWT_SECRET }}
          Jwt__Issuer: "BankSimple"
          Jwt__Audience: "BankSimpleClients"
        run: dotnet test tests/ --verbosity normal
